notifications:
  email: false
git:
  quiet: true
  depth: false
language: java
jdk: openjdk8
node_js: lts/*
python: 3.7
os: linux
addons:
  apt:
    update: true
    packages:
      - python3-setuptools
      - python3-pip
      - sudo
      - lsof
      - curl
install: true
before_install:
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master ;
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
  - stop_any 80 5432 8080 8081 8082 8083 8084 8085 8086 8087 8088
  #
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user --upgrade pip
  - pip install --user --upgrade httpie
jobs:
  include:
    - stage: test
      jdk: openjdk11
      name: test openjdk11
      script:
        - ./mvnw clean compile
        - java -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -cp "target/dependency/*:target/classes" daggerok.App &
        - wait_for 8080
        - http :8080
        - http :8080/
        - http :8080/index.html
        - http :8080/api/hello
        - http :8080/hot-found
        - stop_any 80 8080
    - stage: test
      jdk: openjdk8
      name: test openjdk8
      script:
        - ./mvnw clean dependency:copy-dependencies compile jar:jar
        - java -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -cp "target/dependency/*:target/*" daggerok.App &
        - wait_for 8080
        - http :8080
        - http :8080/
        - http :8080/index.html
        - http :8080/api/hello
        - http :8080/hot-found
        - stop_any 80 8080
    - stage: test
      jdk: openjdk11
      name: test jat openjdk11
      script:
        - ./mvnw clean package
        - java -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -jar target/*-all.jar &
        - wait_for 8080
        - http :8080
        - http :8080/
        - http :8080/index.html
        - http :8080/api/hello
        - http :8080/hot-found
        - stop_any 80 8080
    - stage: test
      jdk: openjdk8
      name: test fat openjdk8
      script:
        - ./mvnw clean package
        - java -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -jar target/*-all.jar &
        - wait_for 8080
        - http :8080
        - http :8080/
        - http :8080/index.html
        - http :8080/api/hello
        - http :8080/hot-found
        - stop_any 80 8080
cache:
  npm: true
  pip: true
  packages: true
  directories:
    - ~/.m2
    - ~/.local/daggerok
